services:
  postgres:
    image: postgres:16

    container_name: bill-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: bills_user
      POSTGRES_PASSWORD: bills_pass
      POSTGRES_DB: bills_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bills_user -d bills_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: